<!DOCTYPE html>
<html>
<head>
    <title>Report Vendor</title>
    <style>
        body {
            font-family: DejaVu Sans, sans-serif;
            font-size: 12px;
            color: #333;
        }

        .header {
            text-align: center;
            margin-bottom: 20px;
        }

        .header h2 {
            margin: 0;
            font-size: 20px;
        }

        .header p {
            margin: 5px 0;
            font-size: 12px;
            color: #777;
        }

        .info {
            margin-bottom: 15px;
        }

        .info table {
            width: 100%;
        }

        .info td {
            padding: 4px;
        }

        .summary {
            margin-top: 10px;
            margin-bottom: 20px;
        }

        .summary-box {
            display: inline-block;
            width: 23%;
            border: 1px solid #ddd;
            padding: 10px;
            margin-right: 1%;
            text-align: center;
            border-radius: 5px;
        }

        .summary-title {
            font-size: 11px;
            color: #888;
        }

        .summary-value {
            font-size: 16px;
            font-weight: bold;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
        }

        th {
            background: #2c3e50;
            color: white;
            padding: 8px;
            font-size: 12px;
        }

        td {
            padding: 8px;
            border: 1px solid #ddd;
        }

        tr:nth-child(even) {
            background: #f2f2f2;
        }

        .footer {
            margin-top: 20px;
            text-align: right;
            font-size: 10px;
            color: #999;
        }
    </style>
</head>
<body>

    <!-- HEADER -->
    <div class="header">
        <h2>LAPORAN VENDOR</h2>
        <p>Agrowisata System</p>
        <p>{{ date('d M Y') }}</p>
    </div>

    <!-- INFO -->
    <div class="info">
        <table>
            <tr>
                <td><strong>Total Vendor:</strong> {{ $data->count() }}</td>
                <td><strong>Total Review:</strong> {{ $data->sum('reviews_count') }}</td>
            </tr>
        </table>
    </div>

    <!-- TABLE -->
    <table>
        <thead>
            <tr>
                <th width="5%">No</th>
                <th>Nama Vendor</th>
                <th width="20%">Total Review</th>
            </tr>
        </thead>
        <tbody>
            @foreach($data as $i => $v)
            <tr>
                <td>{{ $i + 1 }}</td>
                <td>{{ $v->name }}</td>
                <td>{{ $v->reviews_count }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <!-- FOOTER -->
    <div class="footer">
        Generated by System | {{ date('H:i') }}
    </div>

</body>
</html>
